array_width                  = 60
attr_fn_like_width           = 70
chain_width                  = 100
disable_all_formatting       = false
edition                      = "2021"
fn_params_layout             = "Tall"
fn_call_width                = 60
force_explicit_abi           = true
hard_tabs                    = false
match_arm_leading_pipes      = "Never"
match_block_trailing_comma   = true
max_width                    = 110
merge_derives                = true
newline_style            = "Auto"
remove_nested_parens     = true
reorder_imports          = true
reorder_modules          = true
single_line_if_else_max_width = 100
struct_lit_width              = 18
struct_variant_width          = 35
tab_spaces                    = 4
use_field_init_shorthand      = true
use_small_heuristics          = "Max"
use_try_shorthand             = true